"""
GA Parameter Explorer — SQLModel Table Definitions
All tables are defined here so SQLModel.metadata is fully populated before
create_all is called.
"""
from datetime import datetime
from typing import Optional

from sqlmodel import Field, SQLModel


# ---------------------------------------------------------------------------
# GA Results Import
# ---------------------------------------------------------------------------

class GASession(SQLModel, table=True):
    """One upload of a GA results CSV file."""
    __tablename__ = "gasession"

    id: Optional[int] = Field(default=None, primary_key=True)
    filename: str = Field(index=True)
    columns: str  # JSON-encoded list[str] of column names
    row_count: int
    created_at: datetime = Field(default_factory=datetime.utcnow)


class GARow(SQLModel, table=True):
    """One row from a GA results CSV, stored as JSON for flexible columns."""
    __tablename__ = "garow"

    id: Optional[int] = Field(default=None, primary_key=True)
    session_id: int = Field(foreign_key="gasession.id", index=True)
    data: str  # JSON: {column_name: value}
    rank: Optional[int] = Field(default=None)


# ---------------------------------------------------------------------------
# OHLCV Price Data Import
# ---------------------------------------------------------------------------

class OHLCVSession(SQLModel, table=True):
    """Metadata for one uploaded OHLCV CSV file."""
    __tablename__ = "ohlcvsession"

    id: Optional[int] = Field(default=None, primary_key=True)
    filename: str = Field(index=True)
    row_count: int
    date_from: Optional[str] = Field(default=None)
    date_to: Optional[str] = Field(default=None)
    columns: str  # JSON-encoded list[str]
    file_path: str = Field(default="")   # disk path to the stored CSV
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Strategy
# ---------------------------------------------------------------------------

class Strategy(SQLModel, table=True):
    """A user-uploaded Python strategy file, stored verbatim in the DB."""
    __tablename__ = "strategy"

    id: Optional[int] = Field(default=None, primary_key=True)
    filename: str = Field(index=True)
    content: str  # Full source code
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Backtest
# ---------------------------------------------------------------------------

class Backtest(SQLModel, table=True):
    """A single backtest run linking GA row → Strategy → OHLCV session."""
    __tablename__ = "backtest"

    id: Optional[int] = Field(default=None, primary_key=True)
    ga_row_id: int = Field(index=True)
    strategy_id: int = Field(index=True)
    ohlcv_session_id: int = Field(index=True)
    status: str = Field(default="pending")   # pending | running | done | error
    error_msg: Optional[str] = Field(default=None)
    trade_count: int = Field(default=0)
    net_profit: Optional[float] = Field(default=None)
    created_at: datetime = Field(default_factory=datetime.utcnow)


class Trade(SQLModel, table=True):
    """Individual trade generated by a backtest."""
    __tablename__ = "trade"

    id: Optional[int] = Field(default=None, primary_key=True)
    backtest_id: int = Field(foreign_key="backtest.id", index=True)
    trade_no: int
    entry_date: str
    exit_date: str
    entry_price: float
    exit_price: float
    direction: str   # 'long' | 'short'
    profit: float
    balance: float


# ---------------------------------------------------------------------------
# Monte Carlo
# ---------------------------------------------------------------------------

class MCRun(SQLModel, table=True):
    """Results of a Monte Carlo simulation for a given backtest."""
    __tablename__ = "mc_run"

    id: Optional[int] = Field(default=None, primary_key=True)
    backtest_id: int = Field(index=True)
    n_simulations: int
    initial_balance: float
    results_json: str  # Compressed stats + packed equity curves as JSON string
    created_at: datetime = Field(default_factory=datetime.utcnow)
